include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true
    always_use_package_imports: true

    # Riverpod
    avoid_dynamic_calls: true

    # Quality
    unawaited_futures: true
    cancel_subscriptions: true
    close_sinks: true

analyzer:
  errors:
    invalid_annotation_target: ignore   # Freezed generates these safely
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
